### ISSUE TITLE
Build and deploy ESDoc using Travis CI

### ISSUE THREAD

**Issue by thms-rmb** [press-js/wp-rest#1]
Currently, ESDoc is used to provide a website documenting the codebase. We use GitHub Pages to serve this from a directory in the repository. 

This is easy, Pages does a lot of work for us. But we would need to make sure to build and commit the docs before pushing any changes to the repo. A lot of diffs in the commit history would include unneccessary information on the html files in the docs directory. Instead, I suggest making Travis CI watch the repo, building and deploying the docs for us after any change to the codebase.

We could use an inexpensive service such as S3 or Google Cloud Storage to serve these docs, since they're all static anyway.

Looking at the build script in `package.json`, we could use a `.travis.yml` file such as this:

```
sudo: false
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
- rm -r -f docs/
script:
- npm run build:docs
after_success:
- google-cloud-sdk/bin/gsutil -m cp -r -z "html,js,css" docs/** gs://press-js-wp-rest-docs
```

The docs would then be available at [https://storage.googleapis.com/press-js-wp-rest-docs](https://storage.googleapis.com/press-js-wp-rest-docs)

What do you think, @esphen?

**Comment by esphen** [comment]
I agree - this first attempt was a quick and dirty solution to the problem. Using travis would be more optimal, and I honestly don't care that much where it's hosted.

If you have time some day, feel free to implement this :)

**Comment by thms-rmb** [comment]
Ah, do you have some sort of Git hook in place? I guess that's a good solution. Still, one of my points still stand: the docs would always be present in the Git history.

I could take us to Travis and the cloud! :-)

**Comment by esphen** [comment]
Yes, the hook is here: https://github.com/press-js/wp-rest/blob/master/package.json#L10
And here: https://github.com/press-js/wp-rest/blob/master/package.json#L22-L29

I agree with your git history and repo pollution argument. To the cloud!
